superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('',RedirectView.as_view(url='/superheroes/'))
    # path('details/',RedirectView.as_view(url='/superheroes/details/'))
]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
  path('', views.index, name='index'),
  path('<int:hero_id>', views.details, name='details'),
  path('new/', views.create, name='create'),
  path('<int:hero_id>/update', views.update, name='update'),
  path('<int:hero_id>/delete', views.delete_hero, name='delete')
  
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
  name = models.CharField(max_length=50)
  alter_ego = models.CharField(max_length=50)
  primary_ability = models.CharField(max_length=50)
  secondary_ability = models.CharField(max_length=50) 
  catch_phrase = models.CharField(max_length=100)

  def __str__(self):
      return self.name

superhero_project/superheroes/views.py
from warnings import catch_warnings
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Superhero

# Create your views here.
def index(request):
  all_heroes = Superhero.objects.all()
  context = {
    'all_heroes': all_heroes
  }
  return render(request, 'superheroes/index.html', context)

def details(request, hero_id):
  single_hero = Superhero.objects.get(pk=hero_id)
  context = {
    'hero': single_hero
  }
  return render(request, 'superheroes/details.html', context)

def create(request):
  if request.method == "POST":
    #save the form as a new db content
    #return to index
    name = request.POST.get('name')
    alter_ego = request.POST.get('alter_ego')
    primary = request.POST.get('primary')        
    secondary = request.POST.get('secondary')
    catchphrase = request.POST.get('catchphrase')
   
    new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
    new_hero.save()
    return HttpResponseRedirect(reverse('superheroes:index'))

  else:
    return render(request, 'superheroes/create.html')


def update(request, hero_id):
  update_hero = Superhero.objects.get(pk=hero_id)
  context = {
      'hero' : update_hero
  }

  if request.method == "POST":
    update_hero.name = request.POST.get('name')
    update_hero.alter_ego = request.POST.get('alter_ego')
    update_hero.primary_ability = request.POST.get('primary')        
    update_hero.secondary_ability = request.POST.get('secondary')
    update_hero.catch_phrase = request.POST.get('catchphrase')
    
    # update_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
    update_hero.save()
    
    return HttpResponseRedirect(reverse('superheroes:index'))

  else:
    return render(request, 'superheroes/update.html', context)
    


def delete_hero(request, hero_id):
  single_hero = Superhero.objects.get(pk=hero_id)
  # context = {
  #   'hero': single_hero
  # }
  # if request.method == 'POST':
  single_hero.delete()

  return HttpResponseRedirect(reverse('superheroes:index'))
  # else:
  #   return render(request, 'superheroes/details.html', context)

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create New Hero</title>
  </head>
  <body>
    <h1>Add a Superhero</h1>
    <form action="{% url 'superheroes:create'%}" method="post">
      {% csrf_token %} Name: <input type="text" name="name" id="name" /><br />
      Alter Ego: <input type="text" name="alter_ego" id="alter_ego" /><br />
      Primary Ability: <input type="text" name="primary" id="primary" /><br />
      Secondary Ability:
      <input type="text" name="secondary" id="secondary" /><br />
      Catchphrase:
      <input type="text" name="catchphrase" id="catchphrase" /><br />
      <input type="submit" value="Add!" />
    </form>
  </body>
</html>

superhero_project/superheroes/templates/superheroes/details.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Superhero Details</title>
  </head>
  <body>
    {% block content %}
    <a href="{% url 'superheroes:index' %}">Return to Superheroes List</a><br />
    <h1 class="my-5">{{hero.name}}</h1>
    <ul>
      <li>
        <h3>Alter Ego:</h3>
        {{hero.alter_ego}}
      </li>
      <li>
        <h3>Primary Ability:</h3>
        {{hero.primary_ability}}
      </li>
      <li>
        <h3>Secondary Ability:</h3>
        {{hero.secondary_ability}}
      </li>
      <li>
        <h3>Catch Phrase:</h3>
        {{hero.catch_phrase}}
      </li>
    </ul>
    <a href="{% url 'superheroes:update' hero.id %}">Update this Hero</a><br />
    <a href="{% url 'superheroes:delete' hero.id %}">Delete this Hero</a><br />
    {% endblock %}
  </body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
{% extends "base.html" %}

<!-- <!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Superhero Index</title>

  </head>
  <body> -->

{% block content %}
<img
  src="/superhero_project\superheroes\images\super_image.jpg"
  alt="Super cool image of superheroes"
/>
<h1>List of Heroes</h1>
<ul>
  {% for hero in all_heroes %}
  <li class="superheroes-li">
    <h2>
      {{hero.name}} -
      <a href="{% url 'superheroes:details' hero.id %}">Click for Details</a>
    </h2>
  </li>
  {% endfor %}
</ul>
<a href="{% url 'superheroes:create' %}" class="btn btn-primary"
  >Add New Hero</a
>
{% endblock %}
<!-- </body>
</html> -->

superhero_project/superheroes/templates/superheroes/update.html
{% extends "base.html" %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Update Superhero</title>
  </head>
  <body>
    {% block content %}
    <a href="{% url 'superheroes:index' %}">Return to Superheroes List</a><br />
    <h1>Update your Superhero</h1>
    <form action="{% url 'superheroes:update' hero.id %}" method="post">
      {% csrf_token %} Name:
      <input type="text" name="name" id="name" value="{{hero.name}}" /><br />
      Alter Ego:
      <input
        type="text"
        name="alter_ego"
        id="alter_ego"
        value="{{hero.alter_ego}}"
      /><br />
      Primary Ability:
      <input
        type="text"
        name="primary"
        id="primary"
        value="{{hero.primary_ability}}"
      /><br />
      Secondary Ability:
      <input
        type="text"
        name="secondary"
        id="secondary"
        value="{{hero.secondary_ability}}"
      /><br />
      Catchphrase:
      <input
        type="text"
        name="catchphrase"
        id="catchphrase"
        value="{{hero.catch_phrase}}"
      /><br />
      <input type="submit" value="Update!" />
    </form>
    {% endblock %}
  </body>
</html>